name: Bump version

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          poetry install --with dev

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create bump and changelog
        run: |
          # Check if any commits since last tag are bumpable
          if poetry run cz bump --dry-run; then
            echo "Found bumpable commits, proceeding with version bump"
            poetry run cz bump --changelog --yes
          else
            echo "No bumpable commits found (docs, style, etc.), skipping version bump"
            exit 0
          fi

      - name: Get new version
        id: version
        run: |
          VERSION=$(poetry version --short)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Push changes
        run: |
          git push origin master --tags

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: "CHANGELOG.md"
          draft: false
          prerelease: ${{ startsWith(steps.version.outputs.version, '0.') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
