name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version increment (auto = based on conventional commits)'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - patch
          - minor
          - major

jobs:
  unit-tests:
    name: Unit Tests and Code Quality
    uses: ./.github/workflows/tests.yaml
    secrets: inherit

  athena-integration:
    name: Athena Integration Tests
    uses: ./.github/workflows/athena-integration.yml
    secrets: inherit

  bigquery-integration:
    name: BigQuery Integration Tests
    uses: ./.github/workflows/bigquery-integration.yml
    secrets: inherit

  redshift-integration:
    name: Redshift Integration Tests
    uses: ./.github/workflows/redshift-integration.yml
    secrets: inherit

  trino-integration:
    name: Trino Integration Tests
    uses: ./.github/workflows/trino-integration.yml
    secrets: inherit

  snowflake-integration:
    name: Snowflake Integration Tests
    uses: ./.github/workflows/snowflake-integration.yml
    secrets: inherit

  release:
    name: Create release
    needs: [unit-tests, athena-integration, bigquery-integration, redshift-integration, trino-integration, snowflake-integration]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          poetry install --with dev

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump version and create changelog
        run: |
          if [ "${{ github.event.inputs.version_type }}" = "auto" ]; then
            echo "🤖 Auto-determining version bump from conventional commits..."
            poetry run cz bump --changelog --yes
          else
            echo "📌 Manual version bump: ${{ github.event.inputs.version_type }}"
            poetry run cz bump --increment ${{ github.event.inputs.version_type }} --changelog --yes
          fi

      - name: Get new version
        id: version
        run: |
          VERSION=$(poetry version --short)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Push changes
        run: |
          git push origin master --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: "CHANGELOG.md"
          draft: false
          prerelease: ${{ startsWith(steps.version.outputs.version, '0.') }}
          make_latest: ${{ !startsWith(steps.version.outputs.version, '0.') }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
