name: Unit Tests

on:
  push:
  pull_request:
  workflow_call:  # Allow workflow reuse

jobs:
  unit-tests:
    name: Unit Tests (All Adapters)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install -U pip poetry
        poetry install

    - name: Run unit tests with coverage (exclude integration tests)
      run: |
        poetry run pytest -m "not integration" --cov=src/sql_testing_library --cov-report=xml

    - name: Upload unit test coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unit-tests
        name: unit-tests-coverage
        fail_ci_if_error: false
